# Generated by Django 5.0.1 on 2025-11-14 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0002_user_email_otp_user_email_otp_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="tenant_logos/"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="plan",
            field=models.CharField(
                choices=[
                    ("basic", "Basic Plan"),
                    ("standard", "Standard Plan"),
                    ("premium", "Premium Plan"),
                    ("enterprise", "Enterprise Plan"),
                    ("custom", "Custom Plan"),
                ],
                default="standard",
                help_text="Tenant subscription plan",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="custom_role_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="permission",
            name="category",
            field=models.CharField(
                choices=[
                    ("master_sheets", "Master Sheets"),
                    ("ims", "Inventory Management System (IMS)"),
                    ("sourcing", "Sourcing"),
                    ("community", "Community"),
                    ("reports", "Reports"),
                    ("settings", "Settings"),
                    ("members", "Member Management"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="user_limit",
            field=models.IntegerField(
                default=40,
                help_text="Maximum number of users allowed (1-1000)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("master_admin", "Master Admin"),
                    ("tenant_owner", "Tenant Owner"),
                    ("manager", "Manager"),
                    ("general_manager", "General Manager"),
                    ("inventory_manager", "Inventory Manager"),
                    ("supervisor", "Supervisor"),
                    ("attendant", "Attendant"),
                    ("accountant", "Accountant"),
                    ("vendor", "Vendor"),
                    ("distributor", "Distributor"),
                    ("employee", "Employee"),
                    ("custom", "Custom Role"),
                ],
                default="employee",
                max_length=30,
            ),
        ),
    ]
