# Generated by Django 5.0.1 on 2026-02-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0004_v2_multi_role_audit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_log_user_id_79f582_idx',
            old_name='audit_log_user_id_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_log_organiz_65d8eb_idx',
            old_name='audit_log_org_id_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_tenant__7f4c3b_idx',
            old_name='users_tenant__b8f2d3_idx',
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='permission',
            name='category',
            field=models.CharField(choices=[('production_planning', 'Production Planning'), ('quality_control', 'Quality Control / AQL'), ('raw_material_inventory', 'Raw Material / Inventory'), ('purchase_procurement', 'Purchase & Procurement'), ('sales_dispatch', 'Sales & Dispatch'), ('sampling_development', 'Sampling / Development'), ('reports_analytics', 'Reports & Analytics'), ('user_management', 'User Management'), ('billing_subscription', 'Billing & Subscription'), ('organization_settings', 'Organization Settings'), ('community', 'Community'), ('master_sheets', 'Master Sheets'), ('members', 'Member Management'), ('settings', 'Settings')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='can_create_roles_up_to',
            field=models.CharField(blank=True, choices=[('master_admin', 'Master Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('operator', 'Operator')], help_text='Highest role this permission allows creating', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic Plan'), ('standard', 'Standard Plan'), ('premium', 'Premium Plan'), ('enterprise', 'Enterprise Plan'), ('custom', 'Custom Plan')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tenant_id',
            field=models.CharField(blank=True, help_text='Display ID e.g. BIND-PNP-0042 (auto-generated if blank)', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_primary_master',
            field=models.BooleanField(default=False, help_text='True only for the 1st Master Admin of the org (absolute control)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('master_admin', 'Master Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('operator', 'Operator'), ('tenant_owner', 'Tenant Owner (legacy)'), ('employee', 'Employee (legacy)'), ('custom', 'Custom Role (legacy)')], default='operator', max_length=30),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='department',
            field=models.CharField(blank=True, help_text='Department scope (for manager / supervisor roles)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='is_default_role',
            field=models.BooleanField(default=False, help_text='Which role to load first after login'),
        ),
    ]
