# Generated by Django 5.0.1 on 2026-02-28 00:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0005_rename_audit_log_user_id_ts_idx_audit_log_user_id_79f582_idx_and_more'),
        ('inventory_management', '0002_component_factorycode_artworkmaterial_packaging_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEssential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('STATIONARY', 'Stationary'), ('PANTRY', 'Pantry'), ('MACHINERY', 'Machinery'), ('HOUSEKEEPING', 'Housekeeping'), ('ELECTRICALS', 'Electricals'), ('HARDWARE_CHEMICALS', 'Hardware & Chemicals'), ('AUDIT_COMPLIANCE', 'Audit & Compliance'), ('IT', 'IT'), ('QC_TOOLS', 'QC Tools'), ('TRAVEL_EXPENSE', 'Travel & Expense'), ('REPAIR', 'Repair'), ('MAINTENANCE', 'Maintenance')], max_length=30)),
                ('code', models.CharField(db_index=True, max_length=100)),
                ('entry_date', models.DateField()),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('sr_no', models.IntegerField(default=1)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('item', models.CharField(blank=True, max_length=255, null=True)),
                ('machine_type', models.CharField(blank=True, max_length=100, null=True)),
                ('component_spec', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('for_field', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reference_image', models.FileField(blank=True, null=True, upload_to='company_essentials/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_company_essentials', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_essentials', to='auth_service.tenant')),
            ],
            options={
                'db_table': 'company_essentials',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'tenant'], name='company_ess_categor_84e0c1_idx'), models.Index(fields=['code'], name='company_ess_code_431e1a_idx')],
            },
        ),
        migrations.CreateModel(
            name='InternalPurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ipo_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('order_type', models.CharField(choices=[('STOCK', 'Stock'), ('SAM', 'Sample')], default='STOCK', max_length=20)),
                ('buyer_code_text', models.CharField(blank=True, default='', max_length=50)),
                ('company_type', models.CharField(blank=True, choices=[('STOCK', 'Stock'), ('SAM', 'Sample')], max_length=10, null=True)),
                ('program_name', models.CharField(max_length=255)),
                ('po_sr_no', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipos', to='inventory_management.buyercode')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ipos', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipos', to='auth_service.tenant')),
            ],
            options={
                'db_table': 'internal_purchase_orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'program_name'], name='internal_pu_tenant__caa9d1_idx'), models.Index(fields=['ipo_code'], name='internal_pu_ipo_cod_aabd7a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('order_date', models.DateField()),
                ('order_time', models.TimeField()),
                ('factory_po_number', models.CharField(blank=True, default='', max_length=100)),
                ('product_category', models.CharField(blank=True, default='', max_length=100)),
                ('category_code', models.CharField(blank=True, default='', max_length=50)),
                ('po_description', models.TextField(blank=True, default='')),
                ('particulars', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('unit_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('payment_terms', models.TextField(blank=True, default='')),
                ('remarks', models.TextField(blank=True, default='')),
                ('last_po_number', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='inventory_management.buyercode')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='auth_service.tenant')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='inventory_management.vendorcode')),
            ],
            options={
                'db_table': 'purchase_orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant'], name='purchase_or_tenant__6d4306_idx'), models.Index(fields=['po_code'], name='purchase_or_po_code_6b03bb_idx')],
            },
        ),
    ]
