# Generated by Django 5.0.1 on 2025-11-14 10:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth_service", "0003_tenant_logo_tenant_plan_user_custom_role_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Order in which department appears in menu"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="auth_service.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "departments",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Order in which segment appears in submenu"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_segments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="inventory_management.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Segment",
                "verbose_name_plural": "Segments",
                "db_table": "segments",
                "ordering": ["department", "display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="VendorCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                ("vendor_name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("gst", models.CharField(db_index=True, max_length=15)),
                ("contact_person", models.CharField(max_length=255)),
                ("email", models.EmailField(db_index=True, max_length=255)),
                ("whatsapp_number", models.CharField(max_length=15)),
                (
                    "alt_whatsapp_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("bank_name", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=50)),
                ("ifsc_code", models.CharField(max_length=11)),
                ("job_work_category", models.CharField(max_length=255)),
                ("job_work_sub_category", models.CharField(max_length=255)),
                ("payment_terms", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_vendor_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_codes",
                        to="auth_service.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor Code",
                "verbose_name_plural": "Vendor Codes",
                "db_table": "vendor_codes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BuyerCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                ("buyer_name", models.CharField(max_length=255)),
                ("buyer_address", models.TextField()),
                ("contact_person", models.CharField(max_length=255)),
                ("retailer", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_buyer_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyer_codes",
                        to="auth_service.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buyer Code",
                "verbose_name_plural": "Buyer Codes",
                "db_table": "buyer_codes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["code"], name="buyer_codes_code_5b29e9_idx"),
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="buyer_codes_tenant__f0a337_idx",
                    ),
                    models.Index(
                        fields=["buyer_name"], name="buyer_codes_buyer_n_9b4a97_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["code"], name="departments_code_9f933a_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["tenant", "is_active"], name="departments_tenant__9806a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="segment",
            index=models.Index(
                fields=["department", "code"], name="segments_departm_e739fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="segment",
            index=models.Index(
                fields=["department", "is_active"], name="segments_departm_cf68b6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="segment",
            unique_together={("department", "code")},
        ),
        migrations.AddIndex(
            model_name="vendorcode",
            index=models.Index(fields=["code"], name="vendor_code_code_d7db74_idx"),
        ),
        migrations.AddIndex(
            model_name="vendorcode",
            index=models.Index(
                fields=["tenant", "created_at"], name="vendor_code_tenant__cfed37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorcode",
            index=models.Index(
                fields=["vendor_name"], name="vendor_code_vendor__dbcf68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorcode",
            index=models.Index(fields=["gst"], name="vendor_code_gst_f74a11_idx"),
        ),
        migrations.AddIndex(
            model_name="vendorcode",
            index=models.Index(fields=["email"], name="vendor_code_email_a4f227_idx"),
        ),
    ]
