# Generated by Django 5.0.1 on 2025-12-20 08:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0003_tenant_logo_tenant_plan_user_custom_role_name_and_more"),
        ("inventory_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sequence", models.PositiveIntegerField(default=1)),
                (
                    "length",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "size_unit",
                    models.CharField(
                        blank=True,
                        choices=[("CMS", "CMS"), ("INCHES", "INCHES"), ("MM", "MM")],
                        default="INCHES",
                        max_length=10,
                    ),
                ),
                ("specifications", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "factory_code_components",
                "ordering": ["product", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="FactoryCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(editable=False, max_length=50, unique=True)),
                ("sku", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("in_production", "In Production"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="factory_codes",
                        to="inventory_management.buyercode",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_factory_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factory_codes",
                        to="auth_service.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factory Code",
                "verbose_name_plural": "Factory Codes",
                "db_table": "factory_codes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArtworkMaterial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("components", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "material_description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "net_consumption",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("R METERS", "R METERS"),
                            ("CM", "CM"),
                            ("Inches", "Inches"),
                            ("Meter", "Meter"),
                            ("KGS", "KGS"),
                            ("Pc", "Pc"),
                            ("Set", "Set"),
                            ("Roll", "Roll"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("placement", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "work_order",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WEAVING", "WEAVING"),
                            ("TUFTING", "TUFTING"),
                            ("QUILTING", "QUILTING"),
                            ("PRINTING", "PRINTING"),
                            ("KNITTING", "KNITTING"),
                            ("EMBROIDERY", "EMBROIDERY"),
                            ("DYEING", "DYEING"),
                            ("BRAIDING", "BRAIDING"),
                            ("CARPET", "CARPET"),
                            ("CUTTING", "CUTTING"),
                            ("STITCHING", "STITCHING"),
                            ("Sewing", "Sewing"),
                            ("PACKAGING", "PACKAGING"),
                            ("OTHERS", "OTHERS"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "artwork_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LABELS (BRAND/MAIN)", "LABELS (BRAND/MAIN)"),
                            ("CARE & COMPOSITION", "CARE & COMPOSITION"),
                            ("TAGS & SPECIAL LABELS", "TAGS & SPECIAL LABELS"),
                            (
                                "FLAMMABILITY / SAFETY LABELS",
                                "FLAMMABILITY / SAFETY LABELS",
                            ),
                            ("RFID / SECURITY TAGS", "RFID / SECURITY TAGS"),
                            ("LAW LABEL / CONTENTS TAG", "LAW LABEL / CONTENTS TAG"),
                            ("HANG TAG SEALS / STRINGS", "HANG TAG SEALS / STRINGS"),
                            (
                                "PRICE TICKET / BARCODE TAG",
                                "PRICE TICKET / BARCODE TAG",
                            ),
                            ("HEAT TRANSFER LABELS", "HEAT TRANSFER LABELS"),
                            (
                                "UPC LABEL / BARCODE STICKER",
                                "UPC LABEL / BARCODE STICKER",
                            ),
                            ("SIZE LABELS (INDIVIDUAL)", "SIZE LABELS (INDIVIDUAL)"),
                            (
                                "ANTI-COUNTERFEIT & HOLOGRAMS",
                                "ANTI-COUNTERFEIT & HOLOGRAMS",
                            ),
                            ("QC / INSPECTION LABELS", "QC / INSPECTION LABELS"),
                            ("BELLY BAND / WRAPPER", "BELLY BAND / WRAPPER"),
                            ("TYVEK LABELS", "TYVEK LABELS"),
                            ("TAFFETA LABELS", "TAFFETA LABELS"),
                            ("INSERT CARDS", "INSERT CARDS"),
                            ("RIBBONS", "RIBBONS"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("size_width", models.CharField(blank=True, max_length=50, null=True)),
                ("size_length", models.CharField(blank=True, max_length=50, null=True)),
                ("size_height", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "size_unit",
                    models.CharField(
                        blank=True,
                        choices=[("CMS", "CMS"), ("INCHES", "INCHES"), ("MM", "MM")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "size_artwork_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "testing_requirement",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "reference_image",
                    models.FileField(
                        blank=True, null=True, upload_to="artwork_materials/references/"
                    ),
                ),
                (
                    "length_quantity",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "length_quantity_for_section",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("surplus", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "surplus_for_section",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "approval",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BUYER'S", "BUYER'S"),
                            ("INITIAL", "INITIAL"),
                            ("IPP", "IPP"),
                            ("PP", "PP"),
                            ("TOP", "TOP"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "specific_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("material", models.CharField(blank=True, max_length=255, null=True)),
                ("colours", models.CharField(blank=True, max_length=255, null=True)),
                ("finishing", models.CharField(blank=True, max_length=255, null=True)),
                ("permanence", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "permanence_file",
                    models.FileField(
                        blank=True, null=True, upload_to="artwork_materials/permanence/"
                    ),
                ),
                (
                    "category_specific_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="See ARTWORK_CATEGORY_FIELDS_SCHEMA for structure",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "factory_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artwork_materials",
                        to="inventory_management.factorycode",
                    ),
                ),
            ],
            options={
                "db_table": "factory_code_artwork_materials",
                "ordering": ["factory_code", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Packaging",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "product_selection",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "packaging_type",
                    models.CharField(
                        choices=[
                            ("STANDARD", "STANDARD"),
                            ("ASSORTED", "ASSORTED (LINK IPC#)"),
                        ],
                        default="STANDARD",
                        max_length=50,
                    ),
                ),
                ("casepack_qty", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "assorted_sku_link",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "factory_code",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packaging",
                        to="inventory_management.factorycode",
                    ),
                ),
            ],
            options={
                "db_table": "factory_code_packaging",
            },
        ),
        migrations.CreateModel(
            name="PackagingMaterial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("components", models.CharField(blank=True, max_length=255, null=True)),
                ("product", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "net_consumption_per_pc",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("R METERS", "R METERS"),
                            ("CM", "CM"),
                            ("Inches", "Inches"),
                            ("Meter", "Meter"),
                            ("KGS", "KGS"),
                            ("Pc", "Pc"),
                            ("Set", "Set"),
                            ("Roll", "Roll"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("work_order", models.CharField(blank=True, max_length=100, null=True)),
                ("placement", models.CharField(blank=True, max_length=500, null=True)),
                ("size_width", models.CharField(blank=True, max_length=50, null=True)),
                ("size_length", models.CharField(blank=True, max_length=50, null=True)),
                ("size_height", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "size_unit",
                    models.CharField(
                        blank=True,
                        choices=[("CMS", "CMS"), ("INCHES", "INCHES"), ("MM", "MM")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "packaging_material_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CARTONS/CORRUGATED BOX", "CARTONS/CORRUGATED BOX"),
                            ("PACKAGING ACCESSORIES", "PACKAGING ACCESSORIES"),
                            ("TAPE", "TAPE"),
                            ("POLYBAG", "POLYBAG"),
                            ("POLY BAG WITH FLAP", "POLY BAG WITH FLAP"),
                            ("POLYSHEET", "POLYSHEET"),
                            ("BALE WRAP", "BALE WRAP"),
                            ("OTHER", "OTHER"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("surplus", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "surplus_for_section",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "approval_against",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("no_of_plys", models.CharField(blank=True, max_length=50, null=True)),
                ("joint_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "bursting_strength",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("guage", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "printing_ref",
                    models.FileField(
                        blank=True, null=True, upload_to="packaging_materials/printing/"
                    ),
                ),
                (
                    "gumming_quality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "punch_holes",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("flap_size", models.CharField(blank=True, max_length=50, null=True)),
                ("guage_gsm", models.CharField(blank=True, max_length=50, null=True)),
                ("roll_width", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "roll_width_unit",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("tape_width", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "tape_width_unit",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "material_specific_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="See PACKAGING_MATERIAL_FIELDS_SCHEMA for structure",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "packaging",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="inventory_management.packaging",
                    ),
                ),
            ],
            options={
                "db_table": "factory_code_packaging_materials",
                "ordering": ["packaging", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PackagingWorkOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("work_order", models.CharField(blank=True, max_length=100, null=True)),
                ("work_order_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "packaging_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_orders",
                        to="inventory_management.packagingmaterial",
                    ),
                ),
            ],
            options={
                "db_table": "factory_code_packaging_work_orders",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "factory_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="inventory_management.factorycode",
                    ),
                ),
            ],
            options={
                "db_table": "factory_code_products",
                "ordering": ["factory_code", "sequence"],
                "unique_together": {("factory_code", "name")},
            },
        ),
        migrations.CreateModel(
            name="ConsumptionMaterial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "component_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "net_consumption",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("R METERS", "R METERS"),
                            ("CM", "CM"),
                            ("Inches", "Inches"),
                            ("Meter", "Meter"),
                            ("KGS", "KGS"),
                            ("Pc", "Pc"),
                            ("Set", "Set"),
                            ("Roll", "Roll"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "unit_additional",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "trim_accessory",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ZIPPERS", "ZIPPERS"),
                            ("VELCRO", "VELCRO"),
                            ("STITCHING THREAD", "STITCHING THREAD"),
                            ("BUTTONS", "BUTTONS"),
                            ("RIVETS", "RIVETS"),
                            ("NIWAR (Webbing/Tapes)", "NIWAR (Webbing/Tapes)"),
                            ("LACE", "LACE"),
                            ("INTERLINING/FUSING", "INTERLINING/FUSING"),
                            ("HOOKS & EYES", "HOOKS & EYES"),
                            ("BUCKLES & ADJUSTERS", "BUCKLES & ADJUSTERS"),
                            ("EYELETS & GROMMETS", "EYELETS & GROMMETS"),
                            ("ELASTIC", "ELASTIC"),
                            ("FELT", "FELT"),
                            ("SHOULDER PADS / CUPS", "SHOULDER PADS / CUPS"),
                            ("TUBULAR KNITS / RIBBING", "TUBULAR KNITS / RIBBING"),
                            ("RFID / EAS TAGS", "RFID / EAS TAGS"),
                            (
                                "PLASTIC CABLE TIES / LOOPS",
                                "PLASTIC CABLE TIES / LOOPS",
                            ),
                            ("FRINGE / TASSELS", "FRINGE / TASSELS"),
                            ("PLASTIC PIPES / RODS", "PLASTIC PIPES / RODS"),
                            ("SEAM SEALING TAPE", "SEAM SEALING TAPE"),
                            ("ADHESIVES / GUNNING", "ADHESIVES / GUNNING"),
                            ("PRE-CUT HEMS / BINDINGS", "PRE-CUT HEMS / BINDINGS"),
                            ("REFLECTIVE TAPES / TRIMS", "REFLECTIVE TAPES / TRIMS"),
                            ("FIRE RETARDANT (FR) TRIMS", "FIRE RETARDANT (FR) TRIMS"),
                            ("REPAIR KITS / PATCHES", "REPAIR KITS / PATCHES"),
                            (
                                "CORD STOPS / CORD LOCKS / TOGGLES",
                                "CORD STOPS / CORD LOCKS / TOGGLES",
                            ),
                            (
                                "D-RINGS / O-RINGS / WEBBING LOOPS",
                                "D-RINGS / O-RINGS / WEBBING LOOPS",
                            ),
                            (
                                "FOAM / WADDING (Pre-Cut Shapes)",
                                "FOAM / WADDING (Pre-Cut Shapes)",
                            ),
                            ("PINS / TAGGING BARBS", "PINS / TAGGING BARBS"),
                            ("MAGNETIC CLOSURES / SNAPS", "MAGNETIC CLOSURES / SNAPS"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("size_width", models.CharField(blank=True, max_length=50, null=True)),
                ("size_length", models.CharField(blank=True, max_length=50, null=True)),
                ("size_height", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "size_unit",
                    models.CharField(
                        blank=True,
                        choices=[("CMS", "CMS"), ("INCHES", "INCHES"), ("MM", "MM")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "testing_requirement",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "testing_requirement_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="consumption_materials/testing/",
                    ),
                ),
                (
                    "length_quantity",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("surplus", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "surplus_for_section",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("approval", models.CharField(blank=True, max_length=100, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "work_order",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WEAVING", "WEAVING"),
                            ("TUFTING", "TUFTING"),
                            ("QUILTING", "QUILTING"),
                            ("PRINTING", "PRINTING"),
                            ("KNITTING", "KNITTING"),
                            ("EMBROIDERY", "EMBROIDERY"),
                            ("DYEING", "DYEING"),
                            ("BRAIDING", "BRAIDING"),
                            ("CARPET", "CARPET"),
                            ("CUTTING", "CUTTING"),
                            ("STITCHING", "STITCHING"),
                            ("Sewing", "Sewing"),
                            ("PACKAGING", "PACKAGING"),
                            ("OTHERS", "OTHERS"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "category_specific_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="See TRIM_CATEGORY_FIELDS_SCHEMA for structure",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumption_materials",
                        to="inventory_management.component",
                    ),
                ),
                (
                    "factory_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumption_materials",
                        to="inventory_management.factorycode",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumption_materials",
                        to="inventory_management.product",
                    ),
                ),
            ],
            options={
                "db_table": "factory_code_consumption_materials",
                "ordering": ["factory_code", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="component",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="inventory_management.product",
            ),
        ),
        migrations.CreateModel(
            name="RawMaterial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "component_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "net_consumption",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("R METERS", "R METERS"),
                            ("CM", "CM"),
                            ("Inches", "Inches"),
                            ("Meter", "Meter"),
                            ("KGS", "KGS"),
                            ("Pc", "Pc"),
                            ("Set", "Set"),
                            ("Roll", "Roll"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("specifications", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_materials",
                        to="inventory_management.component",
                    ),
                ),
                (
                    "factory_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_materials",
                        to="inventory_management.factorycode",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_materials",
                        to="inventory_management.product",
                    ),
                ),
            ],
            options={
                "db_table": "factory_code_raw_materials",
                "ordering": ["factory_code", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "work_order",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WEAVING", "WEAVING"),
                            ("TUFTING", "TUFTING"),
                            ("QUILTING", "QUILTING"),
                            ("PRINTING", "PRINTING"),
                            ("KNITTING", "KNITTING"),
                            ("EMBROIDERY", "EMBROIDERY"),
                            ("DYEING", "DYEING"),
                            ("BRAIDING", "BRAIDING"),
                            ("CARPET", "CARPET"),
                            ("CUTTING", "CUTTING"),
                            ("STITCHING", "STITCHING"),
                            ("Sewing", "Sewing"),
                            ("PACKAGING", "PACKAGING"),
                            ("OTHERS", "OTHERS"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("wastage", models.CharField(blank=True, max_length=50, null=True)),
                ("for_field", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "for_section",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "machine_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "quilting_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "printing_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dyeing_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("design", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "image_ref",
                    models.FileField(
                        blank=True, null=True, upload_to="work_orders/images/"
                    ),
                ),
                (
                    "approval_against",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BUYER'S SAMPLE", "BUYER'S SAMPLE"),
                            ("INITIAL SAMPLE", "INITIAL SAMPLE"),
                            ("PP SAMPLE", "PP SAMPLE"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "process_specific_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='\n        Stores process-specific fields:\n        \n        WEAVING: {\n            "reed": "", "pick": "",\n            "warp": true/false, "weft": true/false,\n            "ratioWarp": "", "ratioWeft": "",\n            "ratioWeightWarp": ""\n        }\n        \n        KNITTING: {\n            "wales": true/false, "courses": true/false,\n            "ratioWales": "", "ratioCourses": "",\n            "ratioWeightWales": ""\n        }\n        \n        DYEING: {\n            "receivedColorReference": "PANTONE/ARS/CSI/PMS",\n            "referenceType": "TPG/TCX/COATED/UNCOAT",\n            "shrinkageWidth": true/false, "shrinkageLength": true/false,\n            "shrinkageWidthPercent": "", "shrinkageLengthPercent": "",\n            "ratioWidth": "", "ratioLength": ""\n        }\n        \n        TUFTING/CARPET: {\n            "pileHeight": "", "tpi": ""\n        }\n        \n        CUTTING: {\n            "cutType": "LAYERED/PANEL", "cutSize": ""\n        }\n        ',
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "raw_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_orders",
                        to="inventory_management.rawmaterial",
                    ),
                ),
            ],
            options={
                "db_table": "factory_code_work_orders",
                "ordering": ["raw_material", "created_at"],
            },
        ),
    ]
